spring:
  application:
    name: hc-sandbox-api

  jackson:
    serialization:
      indent_output: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # 8081 is the hc-auth-api Docker container port
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
  level:
    root: INFO
    com.hedgecourt: DEBUG

  springdoc:
api-docs:
  enabled: true
swagger-ui:
  enabled: true

hc:
  common: value

---
spring:
  config:
    activate:
      on-profile: dev

hc:
  env: dev
  test: foo

---
spring:
  config:
    activate:
      on-profile: test

hc:
  env: test
  test: bar

---
spring:
  config:
    activate:
      on-profile: prod

hc:
  env: prod
  test: baz
